Repository NagiosEnterprises/ncpa, pull requests merged in 2024-02, with the labels that each got.

#1109 Fix crash on chown of non-existant ncpa passive log file
  agent/ncpa.py
Labels: Enhancement, 3.X.X

#1102 Fix crash on use of ssl_ciphers option
  agent/ncpa.py
Labels: Approved, 3.X.X

#1115 Improving process checking in MR #1107 so it doesn't crash if NCPA wasn't already running
  CHANGES.rst
  agent/ncpa.py
Labels: 3.X.X

#1107 Improve process ID checking
  CHANGES.rst
  agent/ncpa.py
Labels: 3.X.X

#1095 Updating the Python and OpenSSL versions used when building NCPA
  CHANGES.rst
  build/build.sh
  build/windows/choco_prereqs.ps1
Labels: 3.X.X

#1111 Added a Log filter to Redact the token from issue #1110
  CHANGES.rst
  agent/ncpa.py
Labels: Enhancement, 3.X.X

#1093 Update windowslogs.py
  README.rst
  agent/listener/windowslogs.py
Labels: 3.X.X
