Repository NagiosEnterprises/ncpa, pull requests merged in 2025-01, with the labels that each got.

#1231 Various improvements to Windows process handling
  CHANGES.rst
  agent/ncpa.py
Labels: Bug, Code Quality, 3.X.X

#1234 Upgrading Windows build to Python 3.13.1
  CHANGES.rst
  build/build_windows.bat
  build/resources/require.win.txt
  build/windows/choco_prereqs.ps1
Labels: 3.X.X, Maintenance/Dependencies

#1229 Adding proper error logging to the WSGIServer
  CHANGES.rst
  agent/ncpa.py
Labels: Bug, Enhancement, 3.X.X

#1228 Fixing process check output perfdata
  CHANGES.rst
  agent/listener/processes.py
Labels: Bug, 3.X.X

#1216 Updated check logging to better handle type errors
  CHANGES.rst
  agent/listener/nodes.py
Labels: Code Quality, 3.X.X

#1233 Update server.py
  BUILDING.rst
  agent/listener/server.py
Labels: Enhancement, 3.X.X

#1243 Fixing upgrades on Windows when Python is upgraded
  build/resources/ncpa.nsi
  build/windows/build_ncpa.py
Labels: Bug, 3.X.X
